"""add job requirements

Revision ID: 029f4e7d95dc
Revises: be7c7a01a32e
Create Date: 2026-08-19 10:03:22.219967

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '029f4e7d95dc'
down_revision: Union[str, Sequence[str], None] = 'be7c7a01a32e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('required_skills', sa.Text(), nullable=True))
    op.add_column('jobs', sa.Column('required_experience', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jobs', 'required_experience')
    op.drop_column('jobs', 'required_skills')
    # ### end Alembic commands ###
