"""add skills to career profiles

Revision ID: 10a65c7117ad
Revises: 029f4e7d95dc
Create Date: 2026-08-19 22:05:09.348308

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '10a65c7117ad'
down_revision: Union[str, Sequence[str], None] = '029f4e7d95dc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('career_profiles', sa.Column('skills', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('career_profiles', 'skills')
    # ### end Alembic commands ###
