"""add notification preferences

Revision ID: 20495087c2fc
Revises: 035d689d60e6
Create Date: 2026-10-06 08:43:54.029323

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '20495087c2fc'
down_revision: Union[str, Sequence[str], None] = '035d689d60e6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('job_alerts_enabled', sa.Boolean(), nullable=False, server_default=sa.true()))
    op.add_column('users', sa.Column('high_match_alerts_enabled', sa.Boolean(), nullable=False, server_default=sa.true()))
    op.add_column('users', sa.Column('digest_notifications_enabled', sa.Boolean(), nullable=False, server_default=sa.true()))
    op.add_column('users', sa.Column('email_notifications_enabled', sa.Boolean(), nullable=False, server_default=sa.true()))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'email_notifications_enabled')
    op.drop_column('users', 'digest_notifications_enabled')
    op.drop_column('users', 'high_match_alerts_enabled')
    op.drop_column('users', 'job_alerts_enabled')
    # ### end Alembic commands ###
