"""add notification read timestamp

Revision ID: 3a19b37e61fc
Revises: 8db3cd234d63
Create Date: 2026-09-09 16:49:19.876589

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3a19b37e61fc'
down_revision: Union[str, Sequence[str], None] = '8db3cd234d63'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notifications', sa.Column('read_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('notifications', 'read_at')
    # ### end Alembic commands ###
