"""add job fingerprint

Revision ID: 6110bc6ffef8
Revises: d3a0359183b7
Create Date: 2026-08-15 18:09:42.774634

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6110bc6ffef8'
down_revision: Union[str, Sequence[str], None] = 'd3a0359183b7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('fingerprint', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_jobs_fingerprint'), 'jobs', ['fingerprint'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_jobs_fingerprint'), table_name='jobs')
    op.drop_column('jobs', 'fingerprint')
    # ### end Alembic commands ###
