"""add remote eligibility to jobs

Revision ID: 66d8821cdd2d
Revises: ad9bfba9d4b1
Create Date: 2026-08-25 09:40:55.465370

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '66d8821cdd2d'
down_revision: Union[str, Sequence[str], None] = 'ad9bfba9d4b1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('remote_eligibility', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jobs', 'remote_eligibility')
    # ### end Alembic commands ###
