"""add candidate location to career profile

Revision ID: ad9bfba9d4b1
Revises: 10a65c7117ad
Create Date: 2026-08-24 21:14:59.929523

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ad9bfba9d4b1'
down_revision: Union[str, Sequence[str], None] = '10a65c7117ad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('career_profiles', sa.Column('candidate_location', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('career_profiles', 'candidate_location')
    # ### end Alembic commands ###
